###
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "Lord_Huebes",
    "password": "password228."
}

###
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2NzQ1MDUyMSwiaWF0IjoxNzY3MzY0MTIxLCJqdGkiOiI3NjkzMGQzMWU3ZTM0MTE1ODlmYzJjYWFkNTE4MjRiNyIsInVzZXJfaWQiOiI1In0.ghYiPVQPjd5WpzUXs2x_LuVx2ece10uUn7453_60Cik"
}

###
GET http://127.0.0.1:8000/users/channel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3MzY1MDI4LCJpYXQiOjE3NjczNjQxMjgsImp0aSI6IjUxOGVkMWI4OWE1ZTQ3ZjJiMWRjOTJmODk1ZDRmMzZkIiwidXNlcl9pZCI6IjUifQ.kLsewJlNSJWeUnxuAp3kSIFrUxIT8vzZpMRk4AhMhTg

###
DELETE http://127.0.0.1:8000/users/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3MzY1MDI4LCJpYXQiOjE3NjczNjQxMjgsImp0aSI6IjUxOGVkMWI4OWE1ZTQ3ZjJiMWRjOTJmODk1ZDRmMzZkIiwidXNlcl9pZCI6IjUifQ.kLsewJlNSJWeUnxuAp3kSIFrUxIT8vzZpMRk4AhMhTg