# Generated by Django 6.0 on 2026-01-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='Channels/AvatarChannel/%Y/%m/%d/'),
        ),
    ]
